# deployment.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: myles-runnerdeploy
  labels:
    runner: {{ .Values.labels.runner }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        runner: {{ .Values.labels.runner }}
    spec:
      repository: {{ .Values.repository }}

